// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class Address
{
    public string Id { get; set; }

    public string BuildingId { get; set; }

    public string ApartmentId { get; set; }

    public bool IsApartment { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
