// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EntitiesAzure;

public partial class Apartment
{
    public string Id { get; set; }

    public string FloorId { get; set; }

    public string Code { get; set; }

    public string Door { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
