// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class Building
{
    public string Id { get; set; }

    public string DistrictId { get; set; }

    public string StreetId { get; set; }

    public string BuildingCompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Code { get; set; }

    public string Doorway { get; set; }

    public int FloorCount { get; set; }

    public int YearBuilt { get; set; }

    public decimal Price { get; set; }

    public string EnergyCertificate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string StatusId { get; set; }
}