// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class BuildingStatusLog
{
    public string BuildingId { get; set; }

    public string StatusId { get; set; }

    public DateTime CreatedAt { get; set; }
}