// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class BuildingImage
{
    public string BuildingImageId { get; set; }

    public string BuildingId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string AltText { get; set; }

    public bool IsCoverImage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}