// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class BuildingCompany
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Cif { get; set; }

    public string Website { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}