// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class DistrictStreet
{
    public string DistrictId { get; set; }

    public string StreetId { get; set; }
}