// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class Floor
{
    public string Id { get; set; }

    public string BuildingId { get; set; }

    public int FloorNumber { get; set; }

    public bool HasLift { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}