// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio.EntitiesAzure;

public partial class Purchase
{
    public string Id { get; set; }

    public string BuildingId { get; set; }

    public string BuildingCompanyId { get; set; }

    public string RequestId { get; set; }

    public DateTime Date { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}