import { Solicitation } from '@/core/domain/models/Solicitation'
import { SolicitationRepository } from '@/core/domain/repositories/SolicitationRepository'

const getAll = async (): Promise<Solicitation[]> => {
  return [
    {
      id: '1',
      address: '123 Main St',
      description: 'Fix the leaky faucet',
      type: 'plumbing',
      cost: 100,
      date: new Date(),
      status: 'canceled',
    },
    {
      id: '2',
      address: '456 Elm St',
      description: 'Paint the living room',
      type: 'painting',
      cost: 200,
      date: new Date(),
      status: 'completed',
    },
    {
      id: '3',
      address: '789 Oak St',
      description: 'Install new kitchen cabinets',
      type: 'carpentry',
      cost: 1500,
      date: new Date(),
      status: 'in_progress',
    },
    {
      id: '4',
      address: '321 Maple St',
      description: 'Repair the roof',
      type: 'roofing',
      cost: 3000,
      date: new Date(),
      status: 'pending',
    },
    {
      id: '5',
      address: '654 Pine St',
      description: 'Install new windows',
      type: 'window',
      cost: 2500,
      date: new Date(),
      status: 'completed',
    },
    {
      id: '6',
      address: '987 Cedar St',
      description: 'Clean the gutters',
      type: 'cleaning',
      cost: 300,
      date: new Date(),
      status: 'in_progress',
    },
    {
      id: '7',
      address: '159 Birch St',
      description: 'Replace the air conditioning unit',
      type: 'HVAC',
      cost: 2000,
      date: new Date(),
      status: 'pending',
    },
    {
      id: '8',
      address: '753 Spruce St',
      description: 'Install new flooring',
      type: 'flooring',
      cost: 1200,
      date: new Date(),
      status: 'completed',
    },
    {
      id: '1',
      address: '123 Main St',
      description: 'Fix the leaky faucet',
      type: 'plumbing',
      cost: 100,
      date: new Date(),
      status: 'pending',
    },
    {
      id: '2',
      address: '456 Elm St',
      description: 'Paint the living room',
      type: 'painting',
      cost: 200,
      date: new Date(),
      status: 'completed',
    },
    {
      id: '3',
      address: '789 Oak St',
      description: 'Install new kitchen cabinets',
      type: 'carpentry',
      cost: 1500,
      date: new Date(),
      status: 'in_progress',
    },
    {
      id: '4',
      address: '321 Maple St',
      description: 'Repair the roof',
      type: 'roofing',
      cost: 3000,
      date: new Date(),
      status: 'pending',
    },
    {
      id: '5',
      address: '654 Pine St',
      description: 'Install new windows',
      type: 'window',
      cost: 2500,
      date: new Date(),
      status: 'completed',
    },
    {
      id: '6',
      address: '987 Cedar St',
      description: 'Clean the gutters',
      type: 'cleaning',
      cost: 300,
      date: new Date(),
      status: 'in_progress',
    },
    {
      id: '7',
      address: '159 Birch St',
      description: 'Replace the air conditioning unit',
      type: 'HVAC',
      cost: 2000,
      date: new Date(),
      status: 'pending',
    },
    {
      id: '8',
      address: '753 Spruce St',
      description: 'Install new flooring',
      type: 'flooring',
      cost: 1200,
      date: new Date(),
      status: 'completed',
    },
  ]
}

export const solicitationApiRepository: SolicitationRepository = {
  getAll,
}
